### ISSUE TITLE
Repository is out-of-date.

### ISSUE THREAD

**Issue by trojanfoe** [CodeAndWeb/PhysicsEditor-Cocos2d-Chipmunk#2]
Am I right in thinking the version of the code in the following repo:

https://github.com/CodeAndWeb/PhysicsEditor-Cocos2D-V3

Is a more up-to-date version of the code from this repo?  If so, could you update it to make it easier to find?

**Comment by CodeAndWeb** [comment]
Well - this all is a bit out of date - it's using cocos2d in ObjC :-)
